export const OPEN_SIDE_DRAWER = 'OPEN_SIDE_DRAWER';
export const CLOSE_SIDE_DRAWER = 'CLOSE_SIDE_DRAWER';
export const SET_SCROLL_STATUS = 'SET_SCROLL_STATUS';
export const SET_IS_SCROLLING_DOWN = 'SET_IS_SCROLLING_DOWN';
export const SET_VERSION = "SET_VERSION";
